type: log

paths:
{{ range $i, $path := .paths }}
 - {{$path}}
{{ end }}

exclude_files:
  - '.gz$'

processors:
  - dissect:
      tokenizer: '[%{time}] [%{tidb.tiflash.level}] [%{tidb.tiflash.source_line}] %{tidb.tiflash.log_message}'
      field: "message"
      target_prefix: ""
      ignore_failure: true
  - timestamp:
      field: time
      ignore_missing: true
      layouts:
        - '2006/01/02 15:04:05.999 -07:00'
      test:
        - '2021/09/02 04:08:27.541 +00:00'
  - drop_fields:
      when:
        has_fields: [ 'tidb.tiflash.source_line' ]
      fields: [ "message", "time" ]
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.11.0
