type: container

paths:
  - /var/log/containers/*tidb*.log

exclude_files:
  - '.gz$'
  - '.*slowlog.*\.log$'

processors:
  - add_kubernetes_metadata:
    host: ${NODE_NAME}
    matchers:
      - logs_path:
          logs_path: "/var/log/containers/"
  - dissect:
      tokenizer: '[%{time}] [%{tidb.tidb.level}] [%{tidb.tidb.source_line}] ["%{tidb.tidb.log_message}"] %{tidb.tidb.log_fields}'
      field: "message"
      target_prefix: ""
      ignore_failure: true
  - timestamp:
      field: time
      layouts:
        - '2006/01/02 15:04:05.999 -07:00'
      test:
        - '2021/09/02 04:08:27.541 +00:00'
  - drop_fields:
      fields: [ "message", "time" ]
  - add_fields:
      target: ''
      fields:
        ecs.version: 1.11.0
